apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-frontend
  name: udagram-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udagram-frontend
  template:
    metadata:
      labels:
        service: udagram-frontend
    spec:
      containers:
      - image: tiendungcmd/udagram-frontend:v1
        name: udagram-frontend
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8100
      restartPolicy: Always      
---
apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8100
  selector:
    app: udagram-frontend
